### PR TITLE
Add a handful of components

### PR DESCRIPTION
**Pull request by NT7S**
Will try to fill this out with a bit more common components later, but wanted to submit what I needed to render one of my projects and see how it goes. If the components are suitable, I'll work on some more.

### CODE REVIEW

**Comment by NT7S** [comment]
BTW, here's the board in question:
empyrean

**Comment by yaqwsx** [comment]
Thank you for your contribution! Overall the components seems reasonable to me. I have only few comments:
- X1 has quite low contrast and lacks some details (e.g. highligh and edge to add some depth); the component looks "plain" for me.
- I don't like the white spots on the button. But it is hard for me to judge how to adjust them as I have no idea how does the button look like in reality

If you don't mind, I prefer merging this pull request once these issues are resolved. If you want to add more components, feel free to submit a new PR!

**Comment by NT7S** [comment]
I can certainly tweak X1 to have better definition. As to the button, that's how it looks (although I suppose a more true rendering of the color would be off-white, so I can change that). Will push the changes in a bit.

**Comment by NT7S** [comment]
New rendering:
empyrean

**Comment by yaqwsx** [comment]
The X1 looks much better now. I noticed one small technical issue - part R_1210_HandSoldering is a copy and not a symlink of R_1210.  After you fix this, I think we are ready to merge!

**Comment by yaqwsx** [comment]
Thank you for your contribution!

**Pull request merged**
