### PR TITLE
Add TO92 Packages

### PR DESCRIPTION
**Pull request by Electro707**
This WIP PR adds TO92 packages.
Footprint drawings that are added are as if commit 437b42df4e83a54b531bf0b3380b780f45667f35:
- TO-92
- TO-92_HandSolder
- TO92_Inline
- TO92-Inline_HandSolder
- TO-92-2
- TO-92-2_Wide
- TO-92_Wide
- TO-92L
- TO-92L_HandSolder
- TO-92L_Inline
- TO-92L_Inline_HandSolder
- TO-92L_Wide

And this is what they look like:
- All: image
- TO92 + TO92-2: image
- TO-92-Wide: image
- TO92-Inline-Wide: image

### CODE REVIEW

**Comment by yaqwsx** [comment]
Seems good to me! Thank you for your contribution!

**Comment by Electro707** [comment]
I think what I added should suffice. I'll merge the branch with master to update it then it can be merged

**Comment by yaqwsx** [comment]
Please, rebase it.

**Comment by Electro707** [comment]
Should be good now

**Pull request merged**
