### PR TITLE
Add THT resistors

### PR DESCRIPTION
**Pull request by Electro707**
A work-in-progress PR for adding THT resistor. 
This resistor has 4 bands with opacity 0, so this is what the resistor would look normally:
image

But with https://github.com/yaqwsx/PcbDraw/pull/78, it will modify the band's color and opacity depending on the resistor value or if it is manually given:
image

TODO:
- [x] Have a script generate this footprint for the many resistor sizes.

### CODE REVIEW

**Comment by Electro707** [comment]
image
So this is what all resistors I plan on adding look like, created with a generator script. 

The larger ones do look odd. Perhaps it would be better to adjust the body's nodes placement per size before applying a scale and transform per resistor size? Needs to experimentation.

**Comment by yaqwsx** [comment]
I agree that the body shape (especially for the large ones) needs a little bit of tweaking. I would also introduce the terminal of the resistors. The floating body with terminals shown only on silkscreen looks weird. I am thinking if adding a slight shadow or gradient to the body would help the appeal of the drawing.

**Comment by Electro707** [comment]
We can always just not include the larger size resistors which don't have a good ratio compared to the original. From a quick look at Digikey for those size resistors, they seems to be all the brick kind.

**Comment by Electro707** [comment]
Per commit 3d0e83e, I made the leads slightly darker (thoughts compared to the previous color) and thicker.
image

**Comment by yaqwsx** [comment]
Hi, first of all, I am sorry for the long delays. There was a lot of catching up with other projects. The new design looks OK to me. Do you consider this as finalized or do you plan to introduce more tweaks?

**Comment by Electro707** [comment]
I probably would want to get rid of the larger resistors as they don't make sense to have this resistor style, and the fact they don't scale nicely.

**Comment by Electro707** [comment]
image
These are the resistors that I felt look alright and not too skewed. Should be good to merge now if you agree with the selected resistors

**Comment by yaqwsx** [comment]
Thanks!

**Pull request merged**
